### ISSUE TITLE
Spine clipping mask problem

### ISSUE THREAD

**Issue by valukard** [playcanvas/playcanvas-spine#27]
I created animation in spine with clipping mask. After import to playcanvas these files and tried to run animation, I’m getting this error;

TypeError: Cannot read property ‘texture’ of undefined
at t.initAttachment (http://launch.playcanvas.com/api/assets/files/Scripts/Library/playcanvas-spine.min.js?id=27919451&branchId=a171ac64-c8db-441f-8ca3-219148ce95ba:3:147858 1)
at t.updateSlot (http://launch.playcanvas.com/api/assets/files/Scripts/Library/playcanvas-spine.min.js?id=27919451&branchId=a171ac64-c8db-441f-8ca3-219148ce95ba:3:152063)
at t.update (http://launch.playcanvas.com/api/assets/files/Scripts/Library/playcanvas-spine.min.js?id=27919451&branchId=a171ac64-c8db-441f-8ca3-219148ce95ba:3:153211)
at t.onUpdate (http://launch.playcanvas.com/api/assets/files/Scripts/Library/playcanvas-spine.min.js?id=27919451&branchId=a171ac64-c8db-441f-8ca3-219148ce95ba:3:155360)
at Function._helper (https://code.playcanvas.com/playcanvas-stable.dbg.js:24546:14)
at Function.update (https://code.playcanvas.com/playcanvas-stable.dbg.js:24554:10 1)
at Application.update (https://code.playcanvas.com/playcanvas-stable.dbg.js:23988:24)
at Application.tick (https://code.playcanvas.com/playcanvas-stable.dbg.js:24343:11 1)
at Application.start (https://code.playcanvas.com/playcanvas-stable.dbg.js:23977:10)
at http://launch.playcanvas.com/editor/scene/js/launch.js:7250:25 1

Example project: 
https://playcanvas.com/project/665578/overview/spine_mask_sample

Any idea?

**Comment by valukard** [comment]
Any news? O_o

**Comment by willeastcott** [comment]
We've just started an investigation. Stay tuned. 😄

**Comment by willeastcott** [comment]
Hey @valukard - please test the update we've made. Hopefully, you're fine now. 😄
